---
name: Backtest

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'v*-backtest'
  release:
    types:
      - published

jobs:

  compile:
    name: Compile
    uses: .github/workflows/compile.yml

  backtest:

    defaults:
      run:
        shell: bash

    name: Backtest
    needs: compile
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deposit: [10000, 100000]
        spread: [1, 10]
        year: [2020]

    steps:

      - uses: actions/download-artifact@v2
        with:
          name: EA

      - name: Test ${{ matrix.year }}.${{ matrix.month }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDeposit: ${{ matrix.deposit }}
          BtDigits: 5
          BtMonths: 1-12
          BtSpread: ${{ matrix.spread }}
          BtYears: ${{ matrix.year }}
          RunOnError: 'show_logs && parse_results $@; exit 0'
          TestExpert: EA31337-Libre
          TestPeriod: M1
