---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**.mq?'
      - '.github/workflows/compile.yml'
      - 'src/include/**'
  push:
    paths:
      - '**.mq?'
      - '.github/workflows/compile.yml'
      - 'src/include/**'

jobs:
  Compile:
    defaults:
      run:
        shell: powershell
        working-directory: src
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: List MQL files
        run: '(Get-ChildItem -Recurse -Path . -Include *.mq[45]).fullname'
        shell: powershell
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337-Libre.mq4
          include: src
          mt-version: 4.0.0.1320
          verbose: true
      - name: Compile for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337-Libre.mq5
          include: src
          mt-version: 5.0.0.2766
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
