---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.git*'
  push:
    paths-ignore:
      - '**.md'
      - '.git*'
  workflow_call:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Uploads source code
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: src
  mt4:
    name: Installs platform (4)
    uses: EA31337/EA-Tester/.github/workflows/platform-linux.yml@dev
    with:
      artifact_name: mt4
      version: 4
  mt5:
    name: Installs platform (5)
    uses: EA31337/EA-Tester/.github/workflows/platform-linux.yml@dev
    with:
      artifact_name: mt5
      version: 5

  compile-ea:
    defaults:
      run:
        shell: powershell
    name: Compile EA
    needs: [checkout, mt4, mt5]
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: src
          path: src
      - uses: actions/download-artifact@v4
        with:
          name: mt${{ matrix.version }}
          path: .mt${{ matrix.version }}
      - name: List MQL files
        run: '(Get-ChildItem -Recurse -Path . -Include *.mq[45]).fullname'
        shell: powershell

      - name: Compiles EA
        uses: fx31337/mql-compile-action@master
        with:
          mt-path: .mt?
          path: src\EA31337-Libre.mq${{ matrix.version }}
          verbose: true

      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EA-Libre.ex${{ matrix.version }}
          path: src/*.ex?
    strategy:
      matrix:
        version: [4, 5]

  clean-up:
    name: Clean-up
    needs: [compile-ea]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v4
        with:
          name: mt?
