---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.git*'
  push:
    paths-ignore:
      - '**.md'
      - '.git*'

jobs:
  mt4:
    name: Installs platform (4)
    uses: EA31337/EA-Tester/.github/workflows/platform-linux.yml@dev
    with:
      artifact_name: .mt4
      version: 4
  mt5:
    name: Installs platform (5)
    uses: EA31337/EA-Tester/.github/workflows/platform-linux.yml@dev
    with:
      artifact_name: .mt5
      version: 5

  compile-ea:
    defaults:
      run:
        shell: powershell
        working-directory: src
    name: Compile EA
    needs: [mt4, mt5]
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/download-artifact@v4

      - name: List MQL files
        run: '(Get-ChildItem -Recurse -Path . -Include *.mq[45]).fullname'
        shell: powershell

      - name: Compiles MQL4
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337-Libre.mq4
          verbose: true

      - name: Compiles MQL5
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337-Libre.mq5
          verbose: true

      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EA-Libre
          path: 'src/*.ex?'

  clean-up:
    name: Clean-up
    needs: [compile-ea]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v4
        with:
          name: mt?
