---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**
  push:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**

jobs:

  Compile:
    defaults:
      run:
        shell: powershell
        working-directory: src
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: List MQL files
        run: '(Get-ChildItem -Recurse -Path . -Include *.mq[45]).fullname'
        shell: powershell
      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337-Libre.mq4
          verbose: true

      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337-Libre.mq5
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EA
          path: 'src/*.ex?'

  Test:

    defaults:
      run:
        shell: bash

    needs: Compile
    runs-on: ubuntu-latest

    strategy:
      matrix:
        month: [1, 2]
        year: [2020]

    steps:

      - uses: actions/download-artifact@v2
        with:
          name: EA

      - name: Test ${{ matrix.year }}.${{ matrix.month }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDeposit: 10000
          BtDigits: 5
          BtMonths: ${{ matrix.month }}
          BtYears: ${{ matrix.year }}
          RunOnError: 'show_logs && parse_results $@; exit 0'
          TestExpert: EA31337-Libre
          TestPeriod: M1
